### ISSUE TITLE
False Positive NPM detection

### ISSUE THREAD

**Issue by Sicks3c** [visma-prodsec/confused#23]
## Summary

Hello Team

Thank you for this awesome tool, I wanted to point out that while I was automating my process I came across a certain `package.json` that gave me all false positive results and I can't figure out why this certain one is giving such a results 

> Located here
https://assets.vimeo.com/package.json

## Screenshot
![Image](https://i.imgur.com/4mUj74g.png)

I tested all of these and all of them are already registered

Best regards

**Comment by joohoi** [comment]
Thanks for opening the issue! 

There are actually two different things going on in here:

## False positives when using git urls
Urls like:
 - git+ssh://
 - git+http://
 - git+https://
 - git+file://

returned false positives. This is now fixed in the PR #24 

## False positives with private scopes

Private scopes like seen in the linked example file:
 - @vimeo/iris
 - @vpr/utils

Cannot be seen externally without access to the scope itself. This means that these will still be reported. If the user is sure that a namespace ( @vimeo or @vpr in the example above) is already registered, it's possible to exclude these from the checks on `confused` command line:

`confused -s "@vimeo/*,@vpr/*" -l npm package.json`

**Comment by joohoi** [comment]
The PR #24 is now merged, so I consider this issue solved and will close it. In case you feel that this is not true or have some additional info, feel free to comment here and we'll reopen the issue. Thanks again for reporting it!
